### ISSUE TITLE
Just a few Questions that need answered!

### ISSUE THREAD

**Issue by cactusmop** [akarnokd/open-ig#1000]
Is there a way to eliminate the ctrl+shift+w cheat code?
1) Are you able to use enemy special tanks? Such as, adding to research once you capture a planet?
-----Not sure if you thought of it or if it is possible to do.
2) What about being able to choose what race to use on Free Play Mode?
3) Capturing a planet gives you the free technology of buildings that are Partially Built. Allowing you to get hypershield and meson gun way to early in the game, in my opinion. Especially as easy it is to do.
-----The original game had glitch that could allow you to obtain the hypershield and meson gun. If you knew the glitch. Atleast I think it is a glitch.
4) Is it possible to give the enemy AI the ability to attack fleets?

If these questions have already been asked and answered, I apologize.

**Comment by akarnokd** [comment]
> Is there a way to eliminate the ctrl+shift+w cheat code?

Cheat codes are currently hard coded and always enabled. Does <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>W</kbd> cause conflict for you?

> Are you able to use enemy special tanks?

If you play them in skirmish or switch to them in campaign via cheats then yes. Otherwise no. This is a limit of the original screen design: there is only room for 7 slots of vehicles.

> Such as, adding to research once you capture a planet?

Only the buildings are shared technologies between races in the campaign. If you capture their planet with something intact, such as Trade Center, you get that technology and there is no need to research it.

> Not sure if you thought of it or if it is possible to do.

The technologies are fixed and you unlock them by researching prerequisites. This comes, again, from the limits of the original games's mechanics.

> What about being able to choose what race to use on Free Play Mode?

Currently this is not possible because you'd need a race selection screen that was not in the original. It is possible to add one to the campaign screen so if you want to contribute, go ahead.

Otherwise, the closest thing would be to mod the game by copying the freeplay data files and changing the default player to one of the other races.

A more convenient way is to play the skirmish, setup your races (you can pick their starting planet) and play from there.

> Capturing a planet gives you the free technology of buildings that are Partially Built.

Probably yes, can't remember right now. If you can pull it of then I think its fine to have those.

> Is it possible to give the enemy AI the ability to attack fleets?

They can attack your fleet if they can see it and is parked in their sight for long time or your fleet happens to be in orbit they decided to attack. The aggressiveness of the AI is a long standing issue.

----

I currently don't have time to work on Open-IG, and frankly, there are many things I'd like to do but the original game's limitations prohibit it. Therefore, I'd rather create a new game one day instead.
