### ISSUE TITLE
Sound fails randomly

### ISSUE THREAD

**Issue by ketain** [akarnokd/open-ig#1002]
I am currently playing the campaign in Version 0.95.210.

Unfortunately the sound stops playing like 10 to 15 minutes of play time.
At that moment it also becomes impossible to send or receive any messages making the game almost impossibel to play :(

Interestingly restarting the game does not always solve the problem. Most of the time one has to restart the game multiple times to "fix" the issue.

**Comment by akarnokd** [comment]
If you are playing it on Linux or Mac, then the sound cutting out is due to the platform itself. I can't do much about it from within the game. You can try newer Java versions but there is no guarantee.

[Here](https://github.com/akarnokd/open-ig/wiki/Troubleshooting) is the troubleshooting page where you may find workarounds.
