### ISSUE TITLE
Website+Video Tribute and Bug Report

### ISSUE THREAD

**Issue by Blakeley00** [akarnokd/open-ig#1004]
Hi guys, I posted here a earlier this year when I was doing a simultaneous playthrough of IG1 & OpenIG, but just wanted to say again what a HUGE fan I am of your work. To demonstrate my love of what you’ve achieved I’ve tributed your project on my new Imperium Galactica website here:
[https://www.blakessanctum.x10.mx/Games/Imperium/](https://www.blakessanctum.x10.mx/Games/Imperium/)
I’ve also created a 2 part Video tour on youtube that shows off your amazing work to the world. I’m going to post them across a bunch of forums too. :)
**Part 1:**
[https://www.youtube.com/watch?v=_CZvTDW9bNI](https://www.youtube.com/watch?v=_CZvTDW9bNI)
**Part 2:**
[https://www.youtube.com/watch?v=ROE_td7mWQY](https://www.youtube.com/watch?v=ROE_td7mWQY)

While creating all this content I found a few possible bugs along the way that I thought I’d list below:

- Noticing video differences between OpenIG English and Original IG1 English copy. The original English copy uses more CGI characters than live action whereas the OpenIG videos are filled with more live action characters reading out their lines (presumably in Hungarian) which sometimes results in the english audio ending long before the video ends eg the escort admiral cutscene at lieutenant level where the actor playing the admiral is still waffling on while you can hear your ship leaving lol!

- Meason Planet guns not using muti fire. In IG1 they fired the earlier types of shots along with the meason shot making them very effective. Now they just fire the meason shots alone leaving your planetary defences weaker (& easier for fighters to avoid fire).

- Got attacked on a planet with 2 strongholds and no tanks. For some reason I was still taken to the tank placement screen with all the grids but with no tanks to place the game just got stuck. I couldn’t start the battle and had to force close the game, reload, destroy the strongholds and lose the planet (sadly all my tanks were on a fleet out of range lol) to avoid the bug! 

- People I’m already allied with keep contacting me offering an alliance. Then my rep drops from 100 down to 91 when I accept their alliance offer!

- Got achievement for researching all techs but I still had 1 to go.

- While filming the youtube video of your mod for youtube I encountered an interesting bug where it told me I had won a battle and was promoted to commander but in actual fact my ship had been blown up and I died as usual shortly after the ‘you won’ message.
[https://youtu.be/ROE_td7mWQY?t=6m4s](https://youtu.be/ROE_td7mWQY?t=6m4s)

- One of the planets from the original game is missing. This could be due to the fact it had a duplicate name however removing the planet completely and leaving a big hole in that part of the galaxy doesn't seem like the best solution. How about renaming it to ‘Exterior 21’ or something?
**Original IG1:**
[https://i.imgur.com/lETLMzg.png](https://i.imgur.com/lETLMzg.png)
**OpenIG:**
[https://i.imgur.com/kKD6VuS.png](https://i.imgur.com/kKD6VuS.png)

Keep up the great work guys. You're the best! :)

**Comment by akarnokd** [comment]
Hi and thanks for the feedback.

> English CGI

It was decided a long ago that all languages use the same FMVs. The small inconvenience of misaligned VO then can be addressed by community contributions.

> Meson Guns

I mostly assumed that was an error in the original version. Meson projectiles are quite powerful in their own. Otherwise, the game balance is always a question because the original had scripted/cheated battles.

> Stronghold defense

This sounds like an UI bug. Opened #1005 for contributions.

> Diplomacy

It never worked consistently and can be largely ignored. 

> Won and lost

The battle screen doesn't consider any particular ship loss as defeat. You technically won the battle but failed the campaign.

>  leaving a big hole in that part of the galaxy doesn't seem like the best solution

There is no need to assume it was deliberate; we never noticed a planet was missing. Opened #1006.

**Comment by Blakeley00** [comment]
Sorry I meant no offence with that assumption. I just made it because the last time I gave you guys some bugs they turned out to be deliberate design/improvement decisions haha. And once again it looks like  half of these new bugs I've reported are actually design deliberate decisions so I just figured the missing planet with the duplicate name might be one of those. Clearly not haha. I think it's a nice ocean planet if I recall. :)

**Comment by akarnokd** [comment]
> I think it's a nice ocean planet if I recall. :)

If you could upload a screenshot of the surface into #1006, we can add the right one.

Nice videos by the way. I wish I had time or motivation working on Open-IG. I think we reached the limits of the original design, no more space to cram in features really. AI, balance, multiplayer are simply beyond my skillset.

The prototype space battle was funny. I don't remember anyone trying to use the nearby planet's defenses against the AI. The odd movement at the end by the Garthog battleships was due to fleeing attempt into the wrong direction; in deep space, they would have been on the right side of the screen and once you destroyed the prototype, they'd simply retreat. (Small tip: you don't have to destroy anything but the prototype to get the Garthog give up the battle.)

For the Dargslan battleship screen, the campaign battleship is in the middle because they are roughly equivalent to a Battleship 2. In skirmish where everyone starts at a low tech level, such ship would have been too strong and too expensive for the early game. The starred versions are there to match the human technology. As you said, the original never intended the player to meet aliens outside the campaign and assets were simply not there.

You can have a bit more fun with [cheats](https://github.com/akarnokd/open-ig/wiki/Game-guide#cheats) btw.

**Comment by Blakeley00** [comment]
No worries I'll got take a screenshot now.

Thanks! Hope it brings some more fans and help your way. :) That's a shame to hear things are slowing down now. Although what you've already achieved is enough for most anyway!

Yeah I think one of the IG1 walkthroughs on GameFAQs suggests you do it to gain an advantage in IG1 so I couldn't resist using the trick whenever I could in OpenIG too haha. Ahh I see, now that their weird behaviour makes sense heh.

**Comment by akarnokd** [comment]
Thanks for the videos and sorry about taking so long to fix some remaining issues. Version [0.95.219](https://github.com/akarnokd/open-ig/releases/tag/v0.95.219) includes the fix for the prototype battle and the visual bug of the database screen.
