### ISSUE TITLE
Planet missing from the campaign

### ISSUE THREAD

**Issue by akarnokd** [akarnokd/open-ig#1006]
From #1004:

> One of the planets from the original game is missing. This could be due to the fact it had a duplicate name

![image](https://user-images.githubusercontent.com/1269832/31574924-c8cb2432-b0da-11e7-8d40-0e34fcbf6cd0.png)

**Comment by Blakeley00** [comment]
I remembered wrong sorry, the missing planet is a snow planet! Here's a screen of all 4 corners which will hopefully give away which snow layout it is.

[https://i.imgur.com/UoiMHKm.png](https://i.imgur.com/UoiMHKm.png)

**Comment by akarnokd** [comment]
Thanks. You can copy-paste images with some browsers into GitHub issues:

![image](https://user-images.githubusercontent.com/1269832/31576383-22a5e234-b0fa-11e7-9c8f-52cdaabbe0d5.png)

**Comment by akarnokd** [comment]
This is on max zoom for determining its location:

![image](https://user-images.githubusercontent.com/1269832/32292950-ee590ed8-bf41-11e7-8a21-36bca3db62ad.png)

**Comment by akarnokd** [comment]
It looks like the Frozen-8 type surface.

**Comment by mansam** [comment]
The missing Exterior 19 is defined in planets.xml. I have a hunch that because it's followed by the definition for the cratered Exterior 19 and shares the same ID that it's being replaced by the second entry. I'm struggling to test this hunch myself though; what's the right way to build the project so that it runs with local data changes instead of what it tries to download from the web?

**Comment by p-smith** [comment]
@mansam You have to extract the contents of the <project-root>\install\open-ig-video-*.zip files into <project-root>\video, then you can use hu.openig.Startup as the main class to start the game.

Basically, the game checks the existence of certain files at startup. If the check is successful, it will use the local data, otherwise it will offer to run the launcher. In a clean repo, the videos are the only data files that are not present when the game starts, all others (data, audio, images, etc.) are fine.

**Comment by akarnokd** [comment]
Thanks for looking into the files. I've fixed this by renaming that planet to **Exterior 23** in a lot of places. Could anybody check if loading an existing save still works?

Closing via https://github.com/akarnokd/open-ig/commit/09143034cb4835414ee1077fbe5ceb9215fb14de
