### ISSUE TITLE
Alliances

### ISSUE THREAD

**Issue by Krusnohorec** [akarnokd/open-ig#1061]
Let's say there is an alien race which has 100 relation with the player. The alien race sends message that they would like to ally with the player. When declined, nothing happens (relations stays 100), but when clicking on accept, relation is decreased to 91. This seems to me not right. However I do not remember how was it in the old game. One more comment, when the alliance proposal is accepted, no alliance is created (as par savegame file, there is no alliance in relations part). Otherwise except of the Test, where I failed, no other bug observed. Thank you for the game!

**Comment by akarnokd** [comment]
Hi. Diplomacy is randomized, hence the counter-intuitive change in relations.

We were unable to figure out how the original did things or how to do it reasonably ourselves.

**Comment by Krusnohorec** [comment]
OK, that's fine. I can imagine it would cost a hell of work to develop a new system with just a little pay off. Thank you again.

**Comment by DrakonAlpha** [comment]
I think it is implemented the same way in the original game. The reason is that the player usually benefits significantly from an alliance. But in order for the player not to become too strong, there has to be some kind of disadvantage to compensate. This disadvantage is exhausted in a decrease of the relationship rating. At least this is my explanations for that.
