### ISSUE TITLE
Ground unit AI

### ISSUE THREAD

**Issue by GoogleCodeExporter** [akarnokd/open-ig#403]
```
I once again have to mention the ground units AI.

Right now they do not attack buildings in Open IG.

I was told that it's making it easier.

But:

1) That way you''ll never have to deal with damages buildings. That's sad. They 
have a damage system for a reason.

and more important:

2) it makes it MORE difficult

In DOS IG some units attacked my units. The rest attacked my buildings. That 
way I could deal with the ones attacking me first and then I could destroy the 
others one by one. Yes, it was expensive because of the buldings loss but I had 
far better chances of actually winning the fight.

As always I can do a video if you can't follow me :)
```

Original issue reported on code.google.com by `norbert....@gmail.com` on 1 May 2012 at 11:55

**Comment by hemoridos** [comment]
This issue is resolved, invading AI splits it's units up nicely for attacking all buildings as well as units. This actually works much better then in the original where they just bee-line to your powerplants or defensive buildings. Now you are forced to respond to them and not just wait until they get to your fortress/powerplant area where you can easily mow them down.
